"""Render gitignored per-task context files for daemon runners."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from . import prompts
from .envs import RunContext
from .task import Task


def write_context_file(
    brr_dir: Path,
    task: Task,
    event: dict[str, Any],
    ctx: RunContext,
    *,
    recent_conversation: list[dict[str, Any]] | None = None,
    event_body: str | None = None,
) -> Path:
    """Write `.brr/runs/<task-id>/context.md` and return its path."""
    context_dir = brr_dir / "runs" / task.id
    context_dir.mkdir(parents=True, exist_ok=True)
    path = context_dir / "context.md"
    path.write_text(
        render_context(
            task, event, ctx,
            recent_conversation=recent_conversation,
            event_body=event_body,
        ),
        encoding="utf-8",
    )
    return path


def render_context(
    task: Task,
    event: dict[str, Any],
    ctx: RunContext,
    *,
    recent_conversation: list[dict[str, Any]] | None = None,
    event_body: str | None = None,
) -> str:
    lines: list[str] = [
        "# brr Run Context",
        "",
        "Generated by brr for the active daemon task. Lives in the gitignored",
        "`.brr/` runtime directory and is safe to read, but agents should not",
        "edit it. The Task Context Bundle in the daemon prompt is the hot",
        "path; open this file only when you need details the bundle didn't",
        "include — exact host paths, container/image metadata, the full",
        "environment-state map, or runtime file locations.",
        "",
        "## Task",
        "",
        f"- Task ID: {task.id}",
        f"- Event ID: {task.event_id}",
        f"- Source: {task.source or event.get('source', '')}",
        f"- Status: {task.status}",
        f"- Environment: {ctx.name}",
        f"- Execution root: {ctx.cwd}",
        f"- Repository root: {ctx.repo_root}",
        f"- Shared runtime dir: {ctx.runtime_dir}",
    ]
    if ctx.branch_plan:
        lines.append(f"- Seed ref: {ctx.branch_plan.seed_ref}")
        if ctx.branch_plan.auto_land_branch:
            lines.append(f"- Auto-land branch: {ctx.branch_plan.auto_land_branch}")
        else:
            lines.append("- Auto-land branch: none (task branch will be preserved)")
        lines.append(f"- Branch source: {ctx.branch_plan.source}")
        if ctx.branch_plan.host_context_branch:
            lines.append(f"- Host context branch: {ctx.branch_plan.host_context_branch}")
    if ctx.branch_name:
        lines.append(f"- Current branch: {ctx.branch_name}")
    if task.conversation_key:
        lines.append(f"- Conversation: {task.conversation_key}")

    lines.extend([
        "",
        "## Delivery",
        "",
        f"- Response path for the runner: {ctx.response_path_env}",
        f"- Response path on the host: {ctx.response_path_host}",
    ])

    if recent_conversation:
        rendered = _render_recent_conversation(recent_conversation)
        if rendered:
            lines.extend(["", "## Recent in this conversation", "", rendered])

    body = (
        event_body if event_body is not None else event.get("body", "") or ""
    ).strip()
    if body:
        lines.extend(["", "## Original Event Body", "", body])

    task_file = ctx.runtime_dir / "tasks" / f"{task.id}.md"
    lines.extend([
        "",
        "## Runtime Files",
        "",
        f"- Event file: {event.get('_path', '')}",
        f"- Task file: {task_file}",
        f"- Response file: {ctx.response_path_host}",
    ])
    if task.conversation_key:
        from . import conversations
        conv_path = conversations.conversation_path(
            ctx.runtime_dir, task.conversation_key,
        )
        lines.append(f"- Conversation log: {conv_path}")
    if ctx.env_state:
        lines.extend(["", "## Environment State", ""])
        for key, value in sorted(ctx.env_state.items()):
            lines.append(f"- {key}: {value}")

    return "\n".join(lines).rstrip() + "\n"


def _render_recent_conversation(records: list[dict[str, Any]]) -> str:
    """Format conversation records as a bullet list for the context file."""
    return prompts.format_recent_conversation(records)
