"""Render gitignored per-run context files for daemon runners."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from . import forge_state, protocol
from .envs import RunContext
from .run import Run, run_manifest_path


def write_prompt_file(brr_dir: Path, task: Run, prompt: str) -> Path | None:
    """Write the assembled wake prompt to `.brr/runs/<run-id>/prompt.md`.

    Unlike the ephemeral trace-dir prompt (cleaned up on successful runs),
    this copy persists so "what did this wake see?" has an honest answer
    after any run — success or failure.  Returns the path written, or ``None``
    on error (non-fatal; the run continues regardless).
    """
    context_dir = brr_dir / "runs" / task.id
    context_dir.mkdir(parents=True, exist_ok=True)
    path = context_dir / "prompt.md"
    try:
        path.write_text(prompt, encoding="utf-8")
        return path
    except OSError:
        return None


def write_context_file(
    brr_dir: Path,
    task: Run,
    event: dict[str, Any],
    ctx: RunContext,
    *,
    recent_conversation: list[dict[str, Any]] | None = None,
    communication_snapshot: dict[str, Any] | None = None,
    history_groups: list[dict[str, Any]] | None = None,
    event_body: str | None = None,
) -> Path:
    """Write `.brr/runs/<run-id>/context.md` and return its path."""
    context_dir = brr_dir / "runs" / task.id
    context_dir.mkdir(parents=True, exist_ok=True)
    path = context_dir / "context.md"
    path.write_text(
        render_context(
            task, event, ctx,
            recent_conversation=recent_conversation,
            communication_snapshot=communication_snapshot,
            history_groups=history_groups,
            event_body=event_body,
        ),
        encoding="utf-8",
    )
    return path


def render_context(
    task: Run,
    event: dict[str, Any],
    ctx: RunContext,
    *,
    recent_conversation: list[dict[str, Any]] | None = None,
    communication_snapshot: dict[str, Any] | None = None,
    history_groups: list[dict[str, Any]] | None = None,
    event_body: str | None = None,
) -> str:
    lines: list[str] = [
        "# brr Run Context",
        "",
        "Generated by brr for the active daemon run. Lives in the gitignored",
        "`.brr/` runtime directory and is safe to read, but agents should not",
        "edit it. The Run Context Bundle in the daemon prompt is the hot",
        "path; open this file only when you need details the bundle didn't",
        "include — exact host paths, container/image metadata, the full",
        "environment-state map, or runtime file locations.",
        "",
        "## Run",
        "",
        f"- Run ID: {task.id}",
        f"- Event ID: {task.event_id}",
        f"- Source: {task.source or event.get('source', '')}",
        f"- Status: {task.status}",
        (
            "- Environment: host — shared checkout; host finalization does "
            "not publish commits. For work that must leave this machine, "
            "switch off the default branch and own the push / PR handoff."
            if ctx.name == "host"
            else f"- Environment: {ctx.name}"
        ),
        f"- Execution root: {ctx.cwd}",
        f"- Repository root: {ctx.repo_root}",
        f"- Shared runtime dir: {ctx.runtime_dir}",
    ]
    if ctx.branch_plan:
        lines.append(f"- Seed ref: {ctx.branch_plan.seed_ref}")
        if ctx.branch_plan.target_branch:
            lines.append(
                f"- Target branch: {ctx.branch_plan.target_branch}"
            )
        elif ctx.name == "worktree":
            lines.append(
                "- Target branch: none (run branch will be published as-is)"
            )
        lines.append(f"- Branch source: {ctx.branch_plan.source}")
        if ctx.branch_plan.host_context_branch:
            lines.append(f"- Host context branch: {ctx.branch_plan.host_context_branch}")
    if ctx.branch_name:
        lines.append(f"- Current branch: {ctx.branch_name}")
    branch_setup_notice = task.meta.get("branch_setup_notice") or ""
    if branch_setup_notice:
        lines.append(f"- Branch setup: {branch_setup_notice}")
    if task.conversation_key:
        lines.append(f"- Conversation: {task.conversation_key}")

    lines.extend([
        "",
        "## Delivery",
        "",
        f"- Response path for the runner: {ctx.response_path_env}",
        f"- Response path on the host: {ctx.response_path_host}",
    ])
    if ctx.outbox_env:
        lines.append(
            f"- Interim-response outbox (drop a file to ship an update "
            f"mid-thought): {ctx.outbox_env}"
        )

    if communication_snapshot:
        rendered = _render_communication_snapshot(communication_snapshot)
        if rendered:
            lines.extend(["", "## Communication Snapshot", "", rendered])
    elif recent_conversation:
        rendered = _render_recent_conversation(recent_conversation)
        if rendered:
            lines.extend(["", "## Recent in this conversation", "", rendered])

    rendered_groups = _render_history_groups(
        history_groups
        or (
            communication_snapshot.get("history_groups", [])
            if communication_snapshot else []
        )
    )
    if rendered_groups and not communication_snapshot:
        lines.extend(["", "## On-Demand Grouped History", "", rendered_groups])

    thread_record = _thread_of_record_line(ctx.repo_root)
    if thread_record:
        lines.extend(["", "## Thread of Record", "", thread_record])

    body = (
        event_body if event_body is not None else event.get("body", "") or ""
    ).strip()
    attachment_paths = protocol.event_attachment_paths(event)
    if body or attachment_paths:
        lines.extend(["", "## Original Event Body", ""])
        if body:
            lines.append(body)
        if attachment_paths:
            lines.extend(["", "Attachments (local image files — open them with Read):"])
            lines.extend(f"- {p}" for p in attachment_paths)

    run_file = run_manifest_path(ctx.runtime_dir / "runs", task.id)
    prompt_file = ctx.runtime_dir / "runs" / task.id / "prompt.md"
    lines.extend([
        "",
        "## Runtime Files",
        "",
        f"- Event file: {event.get('_path', '')}",
        f"- Run manifest: {run_file}",
        f"- Response file: {ctx.response_path_host}",
        f"- Assembled wake prompt: {prompt_file} (written once the run starts)",
    ])
    if ctx.outbox_host:
        lines.append(f"- Interim-response outbox: {ctx.outbox_host}")
    if task.conversation_key:
        from . import conversations
        conv_path = conversations.conversation_path(
            ctx.runtime_dir, task.conversation_key,
        )
        lines.append(f"- Conversation log: {conv_path}")
    if ctx.env_state:
        lines.extend(["", "## Environment State", ""])
        for key, value in sorted(ctx.env_state.items()):
            lines.append(f"- {key}: {value}")

    return "\n".join(lines).rstrip() + "\n"


def _render_recent_conversation(records: list[dict[str, Any]]) -> str:
    """Format conversation records as a bullet list for the context file."""
    bullets: list[str] = []
    for record in records:
        kind = record.get("kind")
        ts = record.get("ts", "")
        if kind == "event":
            body = record.get("body")
            summary = (
                body.strip() if isinstance(body, str)
                else (record.get("summary") or "").strip()
            )
            source = record.get("source") or ""
            bullets.append(f"- {ts} event ({source}): {summary}".rstrip())
        elif kind == "run":
            tid = record.get("run_id", "")
            status = record.get("status") or "pending"
            branch = (
                record.get("publish_branch")
                or record.get("target_branch")
                or record.get("branch_name")
                or ""
            )
            bullets.append(
                f"- {ts} run {tid} status={status} branch={branch}".rstrip()
            )
        elif kind == "update":
            ptype = record.get("type") or ""
            tid = record.get("run_id") or ""
            stage = record.get("stage") or ""
            bits = [f"- {ts} update {ptype}"]
            if tid:
                bits.append(f"run={tid}")
            if stage:
                bits.append(f"stage={stage}")
            bullets.append(" ".join(bits))
        elif kind == "artifact":
            label = record.get("label") or record.get("artifact_kind") or ""
            body = record.get("body")
            if isinstance(body, str) and body.strip():
                bullets.append(f"- {ts} artifact {label}: {body.strip()}".rstrip())
            else:
                path = record.get("path") or ""
                bullets.append(f"- {ts} artifact {label} {path}".rstrip())
    return "\n".join(bullets)


def _render_communication_snapshot(snapshot: dict[str, Any]) -> str:
    lines: list[str] = []
    current = str(snapshot.get("current_thread") or "").strip()
    if current:
        lines.append(f"- Current thread: {current}")
    correspondent = str(snapshot.get("correspondent_key") or "").strip()
    if correspondent:
        lines.append(f"- Correspondent: {correspondent}")
    failure = snapshot.get("prior_failure")
    if isinstance(failure, dict) and failure:
        reason = str(failure.get("reason") or "").strip() or "no reply produced"
        bits: list[str] = []
        stage = str(failure.get("stage") or "").strip()
        if stage:
            bits.append(f"stage={stage}")
        attempts = failure.get("attempts")
        if isinstance(attempts, int):
            bits.append(f"{attempts} attempt(s)")
        if failure.get("timed_out"):
            bits.append("timed out")
        exit_code = failure.get("exit_code")
        if isinstance(exit_code, int):
            bits.append(f"exit {exit_code}")
        ts = str(failure.get("ts") or "").strip()
        if ts:
            bits.append(ts)
        detail = f" [{'; '.join(bits)}]" if bits else ""
        lines.append(
            f"- Prior run on this thread failed (operational): {reason}{detail}"
        )
    related = snapshot.get("related_threads")
    if isinstance(related, list) and related:
        lines.append("- Related input threads:")
        for thread in related:
            if not isinstance(thread, dict):
                continue
            key = str(thread.get("conversation_key") or "").strip()
            if not key:
                continue
            source = str(thread.get("source") or "").strip()
            records = thread.get("record_count", 0)
            dialogue = thread.get("dialogue_count", 0)
            latest = str(thread.get("latest_ts") or "").strip()
            detail = f"{dialogue} dialogue / {records} records"
            if source:
                detail = f"{source}; {detail}"
            if latest:
                detail = f"{detail}; latest {latest}"
            lines.append(f"  - {key} ({detail})")
    groups = _render_history_groups(snapshot.get("history_groups", []))
    if groups:
        lines.extend(["- On-demand grouped history:", groups])
    forge = _render_forge_state(snapshot.get("forge"))
    if forge:
        lines.extend(["", forge])
    recent = snapshot.get("recent_turns")
    if isinstance(recent, list) and recent:
        rendered = _render_recent_conversation(recent)
        if rendered:
            lines.extend(["", "Recent turns:", rendered])
    return "\n".join(lines)


def _render_pr_state(pr_state: Any) -> list[str]:
    """PR-cache trustworthiness + open PRs with no local worktree (plain)."""
    lines: list[str] = []
    note = forge_state.pr_state_note(pr_state)
    if note:
        lines.append(f"- {note}")
    if not isinstance(pr_state, dict):
        return lines
    standalone, omitted = forge_state.standalone_prs(pr_state)
    if standalone:
        lines.append("- PRs in flight or just resolved (no local worktree):")
        for pr in standalone:
            marker = forge_state.format_pr(pr)
            if not marker:
                continue
            branch = str(pr.get("branch") or "").strip()
            branch_bit = f" ({branch})" if branch else ""
            url = str(pr.get("url") or "").strip()
            link = (
                f" — {url}"
                if url and str(pr.get("state") or "").upper() == "OPEN"
                else ""
            )
            lines.append(f"  - {marker}{branch_bit}{link}")
        if omitted:
            noun = "resolution" if omitted == 1 else "resolutions"
            lines.append(f"  - {omitted} older {noun} in the last 24h omitted")
    return lines


def _render_forge_state(forge: Any) -> str:
    """Render the forge-state facet for the context file (plain, no backticks)."""
    if not isinstance(forge, dict) or not forge:
        return ""
    lines: list[str] = ["Forge state (local, network-free):"]
    worktrees = forge.get("worktrees")
    worktree_summary = forge_state.summarize_worktrees(worktrees)
    if worktree_summary["total"]:
        bits = [f"{worktree_summary['total']} total"]
        if worktree_summary["unpushed_branches"]:
            branches = worktree_summary["unpushed_branches"]
            commits = worktree_summary["unpushed_commits"]
            commit_noun = "commit" if commits == 1 else "commits"
            bits.append(
                f"{branches} with unpushed commits ({commits} {commit_noun})"
            )
        if worktree_summary["dirty_branches"]:
            bits.append(f"{worktree_summary['dirty_branches']} dirty")
        if worktree_summary["current_branches"]:
            bits.append(f"{worktree_summary['current_branches']} current")
        lines.append(f"- Worktrees / branches: {'; '.join(bits)}")
        for wt in worktree_summary["attention"]:
            branch = str(wt.get("branch") or "").strip() or "(detached)"
            tid = str(wt.get("run_id") or "").strip()
            bits: list[str] = []
            unpushed = wt.get("unpushed", 0)
            if isinstance(unpushed, int) and unpushed > 0:
                bits.append(f"{unpushed} unpushed")
            if wt.get("dirty"):
                bits.append("uncommitted changes")
            if wt.get("current"):
                bits.append("this run")
            detail = f" ({'; '.join(bits)})" if bits else ""
            tag = f" [{tid}]" if tid else ""
            url = str(wt.get("branch_url") or "").strip()
            link = f" — {url}" if url else ""
            pr = forge_state.format_pr(wt.get("pr"))
            pr_marker = f" → {pr}" if pr else ""
            lines.append(f"  - {branch}{tag}{detail}{pr_marker}{link}")
        omitted = worktree_summary["omitted"]
        if omitted:
            noun = "branch" if omitted == 1 else "branches"
            lines.append(f"  - {omitted} clean pushed {noun} omitted")
    threads = forge.get("threads")
    if worktree_summary["total"] or (isinstance(threads, list) and threads):
        # Only speak about PR state when the block has a body at all.
        lines.extend(_render_pr_state(forge.get("pr_state")))
    if isinstance(threads, list) and threads:
        lines.append("- Issues / PRs in play:")
        for th in threads:
            if not isinstance(th, dict):
                continue
            repo = str(th.get("repo") or "").strip()
            number = th.get("number")
            ref = f"{repo}#{number}" if repo and number is not None else ""
            if not ref:
                continue
            bits = []
            kind = str(th.get("kind") or "").strip()
            if kind:
                bits.append(kind)
            branch_target = str(th.get("branch_target") or "").strip()
            if branch_target:
                bits.append(f"branch {branch_target}")
            if th.get("current"):
                bits.append("this thread")
            detail = f" ({'; '.join(bits)})" if bits else ""
            url = str(th.get("url") or "").strip()
            link = f" — {url}" if url else ""
            lines.append(f"  - {ref}{detail}{link}")
    if len(lines) == 1:
        return ""
    return "\n".join(lines)


def _render_history_groups(groups: Any) -> str:
    if not isinstance(groups, list) or not groups:
        return ""
    bullets: list[str] = []
    for group in groups:
        if not isinstance(group, dict):
            continue
        label = str(group.get("label") or group.get("id") or "").strip()
        path = str(group.get("path") or "").strip()
        if not label or not path:
            continue
        count = group.get("record_count", 0)
        bullets.append(f"  - {label}: {path} ({count} records)")
    return "\n".join(bullets)


def _thread_of_record_line(repo_root: Path) -> str:
    from . import config as conf
    from . import dominion

    cfg = conf.load_config(repo_root)
    if not bool(cfg.get("dominion.enabled", cfg.get("dominion_enabled", True))):
        return ""
    path = None
    for candidate in dominion.resident_dominion_candidates(repo_root, cfg):
        if candidate.path.is_dir():
            path = candidate.path
            break
    if path is None:
        return ""
    record_path = path / "thread-of-record.md"
    state = "exists" if record_path.exists() else "not created yet"
    return (
        f"- Resident-maintained note: {record_path} ({state}).\n"
        "- Use it for durable cross-channel project narrative when the "
        "current work produces something worth carrying forward."
    )
