<script lang="ts">
	import { onMount } from 'svelte';
	import { pitchAccent } from './statusPalette';
	import { BRNRD_COLORS, type BrnrdConstants, type BrnrdFrame } from './brandGeometry';
	import {
		CYBERPAL_DEFAULTS,
		CYBERPAL_FIRST_MS,
		CYBERPAL_PERIOD_MS,
		buildCycle,
		faceForFrame,
		inkedBody,
		markBox
	} from './cyberpalMark';

	interface Props {
		/** Accessible name; the drawing is presentational. */
		label?: string;
		class?: string;
		/**
		 * Wire-supplied mood frames (#566), same contract as the text wink this
		 * component succeeds: the daemon's `b<eye><mouth><eye>d` grammar. The
		 * first frame is the mood's resting face and picks which drawn face the
		 * being wears between winks. Null/empty ⇒ the neutral rest face.
		 */
		frames?: string[] | null;
		/** `mood_pitch` ∈ [0,1] tinting the ink via `pitchAccent`; null ⇒ inherit. */
		pitch?: number | null;
		/** Geometry override — the bench passes its live sliders through here. */
		constants?: BrnrdConstants;
		/** Sway the whole body like a chibi; reduced-motion always stills it. */
		sway?: boolean;
	}

	let {
		label = 'brnrd',
		class: klass = '',
		frames = null,
		pitch = null,
		constants = CYBERPAL_DEFAULTS,
		sway = true
	}: Props = $props();

	let base = $derived(faceForFrame(frames?.[0]));
	let cycle = $derived(buildCycle(base));
	let box = $derived(markBox(constants));
	let accent = $derived(pitchAccent(pitch));

	// null = at rest (the base face); otherwise the cycle beat index. Same
	// machinery as the text wink: a timer walks the cycle, then settles.
	let beat = $state<number | null>(null);

	let shown = $derived<BrnrdFrame>(beat === null ? base : (cycle[beat]?.frame ?? base));
	let glitching = $derived(beat !== null && (cycle[beat]?.glitch ?? false));
	let body = $derived(inkedBody(shown, constants, 'currentColor'));

	onMount(() => {
		// Reduced-motion readers get the resting face, permanently — the sway
		// is stilled separately, in CSS, by the same media query.
		if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;
		let step: ReturnType<typeof setTimeout> | undefined;
		const wink = () => {
			let i = 0;
			const advance = () => {
				if (i < cycle.length) {
					beat = i;
					const hold = cycle[i].hold;
					i += 1;
					step = setTimeout(advance, hold);
				} else {
					beat = null;
				}
			};
			advance();
		};
		const first = setTimeout(wink, CYBERPAL_FIRST_MS);
		const loop = setInterval(wink, CYBERPAL_PERIOD_MS);
		return () => {
			clearTimeout(first);
			clearInterval(loop);
			if (step) clearTimeout(step);
		};
	});
</script>

<!--
	The mark is drawn, not typed: the five-slot geometry from
	`brandGeometry.ts`, inline, ink from `currentColor` so it sits in any
	text colour it inherits. Glitch beats stack the red/cyan aberration
	ghosts under the body — the screen register's own trick, played live.
	The sway is a slow rocking around the baseline's centre: transform-box
	makes the SVG group honour a CSS transform-origin, so the being tips on
	its feet instead of orbiting the viewBox corner.
-->
<span class="cyberpal {klass}" style={accent ? `color: ${accent}` : undefined}>
	<svg
		viewBox="{box.x} {box.y} {box.w} {box.h}"
		role="img"
		aria-label={label}
		preserveAspectRatio="xMidYMid meet"
	>
		<g class="cyberpal-body" class:cyberpal-sway={sway}>
			{#if glitching}
				<g
					fill="none"
					stroke={BRNRD_COLORS.RED}
					stroke-width={constants.STROKE}
					stroke-linecap="round"
					stroke-linejoin="round"
					opacity="0.55"
					transform="translate(-7,0)"
					aria-hidden="true"
				>
					<!-- eslint-disable-next-line svelte/no-at-html-tags -- geometry generated by our own brandGeometry, no user input -->
					{@html inkedBody(shown, constants, BRNRD_COLORS.RED)}
				</g>
				<g
					fill="none"
					stroke={BRNRD_COLORS.CYAN}
					stroke-width={constants.STROKE}
					stroke-linecap="round"
					stroke-linejoin="round"
					opacity="0.55"
					transform="translate(7,0)"
					aria-hidden="true"
				>
					<!-- eslint-disable-next-line svelte/no-at-html-tags -- same generated geometry as above -->
					{@html inkedBody(shown, constants, BRNRD_COLORS.CYAN)}
				</g>
			{/if}
			<g
				fill="none"
				stroke="currentColor"
				stroke-width={constants.STROKE}
				stroke-linecap="round"
				stroke-linejoin="round"
			>
				<!-- eslint-disable-next-line svelte/no-at-html-tags -- geometry generated by our own brandGeometry, no user input -->
				{@html body}
			</g>
		</g>
	</svg>
</span>

<style>
	.cyberpal {
		display: inline-flex;
		align-items: center;
	}
	.cyberpal svg {
		height: 1.6em;
		width: auto;
		overflow: visible;
	}
	.cyberpal-body {
		transform-box: view-box;
		transform-origin: 50% 96%;
	}
	.cyberpal-sway {
		animation: cyberpal-sway 3.8s ease-in-out infinite alternate;
	}
	@keyframes cyberpal-sway {
		from {
			transform: rotate(-2.6deg);
		}
		to {
			transform: rotate(2.6deg);
		}
	}
	@media (prefers-reduced-motion: reduce) {
		.cyberpal-sway {
			animation: none;
		}
	}
</style>
