import {loadFont as lMono} from '@remotion/google-fonts/GeistMono';
import {loadFont as lSerif} from '@remotion/google-fonts/InstrumentSerif';
import {loadFont as lPix} from '@remotion/google-fonts/Silkscreen';
import {loadFont as lSans} from '@remotion/google-fonts/InterTight';
import {loadFont as lAnton} from '@remotion/google-fonts/Anton';
import {loadFont as lDoto} from '@remotion/google-fonts/Doto';
import {loadFont as lBodoni} from '@remotion/google-fonts/BodoniModa';
import {loadFont as lBar} from '@remotion/google-fonts/LibreBarcode128';
const mono = lMono('normal', {weights: ['400', '500', '600'], subsets: ['latin']});
const serif = lSerif('normal', {weights: ['400'], subsets: ['latin']});
const serifI = lSerif('italic', {weights: ['400'], subsets: ['latin']});
const pix = lPix('normal', {weights: ['400'], subsets: ['latin']});
const sans = lSans('normal', {weights: ['300', '500', '600', '700', '800'], subsets: ['latin']});
const anton = lAnton('normal', {weights: ['400'], subsets: ['latin']});
const doto = lDoto('normal', {weights: ['900'], subsets: ['latin']});
const bodoni = lBodoni('normal', {weights: ['400', '700'], subsets: ['latin']});
const bar = lBar('normal', {weights: ['400'], subsets: ['latin']});
export const F = {MONO: `"${mono.fontFamily}"`, SERIF: `"${serif.fontFamily}"`, PIX: `"${pix.fontFamily}"`, SANS: `"${sans.fontFamily}"`,
  ANTON: `"${anton.fontFamily}"`, DOTO: `"${doto.fontFamily}"`, BODONI: `"${bodoni.fontFamily}"`, BAR: `"${bar.fontFamily}"`};
export const FONTS_READY = Promise.all([mono, serif, serifI, pix, sans, anton, doto, bodoni, bar].map((f) => f.waitUntilDone())).then(() => document.fonts.ready);
